services:
  web:
    build:
      context: ./MessagingService
      dockerfile: Dockerfile
    ports:
      - "5266:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=MessagingServiceDB;Username=postgres;Password=sn90fr77

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sn90fr77
      - POSTGRES_DB=MessagingServiceDB


