// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserTableApp;

#nullable disable

namespace MessagingService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250225192038_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserTableApp.Models.User", b =>
                {
                    b.Property<string>("Login")
                        .HasColumnType("text");

                    b.HasKey("Login");

                    b.ToTable("user");
                });
#pragma warning restore 612, 618
        }
    }
}
